- module.yaml
The chart name should now be in `chart.name` instead of `chart`.
> M4DModule: updated to match spec update

- afm/auth.py
- afm/auth_handlers/auth_servers.py
- afm/config.py
- afm/server.py
- sample/sample.py
- sample/sample.yaml
AFMAuthHandler supports both 'basic' and 'none'
in the 'basic' case, the token returned to the user is the the username (as in https://github.com/apache/arrow/blob/master/python/pyarrow/tests/test_flight.py#L426). Is that a problem?
In `sample/sample.py`, I copied the definition of class HttpBasicClientAuthHandler from `afm/flight/auth_handlers.py` . Is there a better way?
> Support Basic Authentication with AFMAuthHandler

- afm/server.py
choose a subset of the columns.
Following the fix, we filter only the relevant columns
(in the schema, not just in the record batches)
> bring back schema column filtering

- helm/afm/templates/NOTES.txt
This PR fixes the name of the service printed in the python example to be the same as the release name.
Closes #89
> Use Release.Name in python example in NOTES.txt. (#89)

- module.yaml
FybrikModule structure changed.  This updates the module.yaml to match that new structure.
Fixes fybrik issue #755: https://github.com/fybrik/fybrik/issues/755
> Updated module to match new module structure

- module.yaml
The `dataformat` field is optional and should not be specified with placeholders for protocols where this field is redundant.
Required by https://github.com/fybrik/fybrik/pull/1060
> Remove arrow dataformat from module.yaml

- afm/pep/actions.py
- afm/pep/test_actions.py
Adding a new method of transformation, where changing each value in the required columns to the hexa representation of the hash value that returned from the python built-in hash() function.
Signed-off-by: Mohammad Nassar <mohammad.nassar@ibm.com>
> HashRedact

- hack/tools/test_module.sh
Related to https://github.com/cert-manager/cert-manager/issues/2908
Fybrik webhook not really ready after "helm install --wait"
This PR contains a temporary workaround is to add sleep command after fybrik installation
> Minor fix to test_module.sh

- helm/afm/files/conf.yaml
- helm/afm/values.sample.yaml
Signed-off-by: Shlomit Koyfman <shlomitk@il.ibm.com>
This PR relates to https://github.com/fybrik/fybrik/pull/1295
Module arguments include:
- assets (instead of read)
- capability (currently unused)
- context (unused)
- labels (unused)
- selector (unused)
- uuid ( to replace extraction from the labels)
> New structure of module arguments

- helm/afm/files/conf.yaml
one arrow-flight server does only transformations
after reading from another arrow-flight server
> support cascading in helm

- afm/pep/base.py
For instance, if the HashRedact transformation configuration
does not include a set of columns, all columns would be transformed
> Support not configuring a list of columns for a transformation.

- afm/filesystems/vault.py
This PR raise exception when Vault credentials are missing.
Currently, when Vault credentials are missing Error message is printed to the module log but the execution of the module continues.
`{"error": "403: {'errors': ['permission denied']}", "DataSetID": "fybrik-notebook-sample/paysim-csv", "ForUser": true, "message": "vault authentication failed", "level": "ERROR", "caller": "vault.py:25", "funcName": "vault_jwt_auth", "time": "2022-03-02T08:42:46+0000", "app.fybrik.io/app-uuid": ""}
{"DataSetID": "fybrik-notebook-sample/paysim-csv", "ForUser": true, "message": "Empty vault authorization response", "level": "ERROR", "caller": "vault.py:34", "funcName": "get_raw_secret_from_vault", "time": "2022-03-02T08:42:46+0000", "app.fybrik.io/app-uuid": ""}
`
Closes #125
> Raise exception when Vault credentials are missing.

- afm/pep/__init__.py
- afm/pep/base.py
- afm/server.py
- sample/sample.yaml
Closes #144
Signed-off-by: mohammad-nassar10 <mohammad.nassar@ibm.com>
> Add transformation ability to write.

- Pipfile
- Pipfile.lock
- afm/server.py
- sample/sample_put.py
Closes #153 
Closes #152 
This PR support `append` write mode. The default write mode is `overwrite`.
In addition, arrow flight version is upgraded to v7 to support writing csv files.
Co-authored-by: Mohammad Nassar <mohammad.nassar@ibm.com>
> Support "append" write mode.

- helm/afm/files/conf.yaml
When changing the arrow-flight-module and the airbyte-module, there is a problem with the arrow-flight-module configuration:
```
connection:
type: flight
flight:
endpoint_url: my-notebook-fybrik-notebook-sample-airbyte-module.fybrik-blueprints
port: 80
flight_command: "{ \"asset\": \"\" }"
```
The flight command does not include the asset name. Hopefully, this PR fixes this problem.
> fix conf.yaml

- module.yaml
This PR updates module.yaml file with new capability to write csv files. CSV write is [supported ](https://arrow.apache.org/docs/python/generated/pyarrow.dataset.write_dataset.html) in arrow version v7 as the current code use.
> Update module.yaml write capability.

- afm/server.py
This PR removes hard-coded `parquet` suffix from the written file basename_template as the written file could be a csv file.
> Fix written file suffix.

- module.yaml
read modules which support the arrow-flight interface.
Also: add FilterAction and AgeFilterAction transformations
to the read capabilities
> support chaining of arrow-flight-module with other

- .github/workflows/push.yml
This PR simplifies infer version section in push.yml workflow:
Versions are created as follows 
- Tags starting with v will be released as what comes after `v`. (e.g. refs/tags/v1.0 -> 1.0).
- Master branch will be released with `master` as version tag for the docker images and
`0.0.0-master` tag for helm chart.
> Simplify infer version section in push.yml workflow.

- helm/afm/values.yaml
This PR changes readOnlyRootFilesystem to false in order to be able to upload test files to the AFM pod.
Temporary fix till https://github.com/fybrik/fybrik/issues/1554 is reolved.
> Change readOnlyRootFilesystem to false in values.yaml

- afm/server.py
This PR adds the file format to the suffix of the written file name, for example, `object1.csv` instead of `object1`
Relates to https://github.com/fybrik/openmetadata-connector/issues/43
> Add file format to the suffix of the written file name.

- hack/test_module.sh
- helm/afm/templates/deployment.yaml
Closes https://github.com/fybrik/fybrik/issues/2082
This PR adds a readiness probe to the deployed pod.
It also fixes a test.
> Adding a readiness probe
