fybrik/arrow-flight-module

- afm/s3.py
The taxonomy in The Mesh for Data should follow these
> secret-provider s3 keys changed

- .travis.yml
- Makefile
- afm/__init__.py
- afm/asset.py
- afm/pep/__init__.py
- afm/pep/actions.py
- afm/pep/base.py
- afm/pep/test_actions.py
- afm/pep/test_base.py
- afm/server.py
- helm/afm/values.sample.yaml
Fixes https://github.com/IBM/the-mesh-for-data-flight-module/issues/9
- Changed code to always transform the schema and not just on the data.
- Enabled verify/test in travis
> Fix: handling schema transformations

- helm/afm/files/conf.yaml
changed `name` field to be filled from `assetID`
Fixes #11
> helm: updated config template

- afm/server.py
Co-authored-by: roee88 <roee88@gmail.com>
> support multiple parquet files

- afm/server.py
Bypass https://issues.apache.org/jira/browse/ARROW-7867
> Fix: reading datasets with empty direcory object

- afm/server.py
Also reverted to to_table for performance
> Fix: schema inference with S3 empty file

- module.yaml
Field spec.type is being removed from M4DModule
Fixes #20 
Signed-off-by: roee88 <roee88@gmail.com>
> Remove type field from the module.yaml

- afm/asset.py
- afm/server.py
> add support for localfs

- afm/server.py
- sample/sample.py
fix read_asset so as not to read entire table to memory
> fix read_asset so as not to read entire table to memory

- afm/pep/actions.py
> improve performance of redaction operation

- afm/pep/actions.py
- sample/sample.py
by default, the experiment runs 3 times
> timing the retrieval of the sample dataset using timeit.

- afm/server.py
the do_get() can handle choosing a subset of the columns. However,
it has to know which columns to filter. That is not the case. The
request for a subset of the columns goes to the get_flight_info()
request, and it is ignored there.
> fix column choosing.

- afm/asset.py
> minor simplification

- afm/asset.py
- afm/config.py
- afm/server.py
(in the future we will add FlightAsset)
> add FileSystemAsset

- afm/asset.py
- afm/flight/flight.py
- afm/pep/actions.py
- afm/server.py
- afm/ticket.py
- sample/flight.yaml
- sample/sample.py
support for splitting data retrieval and data transformation
> add support for passthrough to another flight server

- Pipfile
- Pipfile.lock
> move to pyarrow 2.0.0

- afm/config.py
- afm/server.py
- afm/worker.py
- sample/sample.py
- sample/sample.yaml
> randomly choose worker from configuration

- afm/server.py
- main.py
> add basic logging messages

- afm/flight/auth_handlers.py
- afm/flight/flight.py
> support basic authentication

- afm/auth.py
- afm/auth_handlers/auth_servers.py
> add some logging to authentication

- afm/filesystems/s3.py
- afm/filesystems/vault.py
- helm/afm/files/conf.yaml
> support getting s3 credentials from vault

- .travis.yml
> attempt to fix travis failure

- .travis.yml
> revert changes to .travis.yml

- .travis.yml
> fix access problem to /etc/docker/certs.d/ghcr.io

- afm/filesystems/s3.py
- afm/filesystems/vault.py
- helm/afm/files/conf.yaml
> fix vault configuration (in conf.yaml)

- helm/afm/files/conf.yaml
- main.py
> take care of each vault field separately

- afm/filesystems/vault.py
> print vault response status code

- afm/asset.py
- afm/filesystems/vault.py
> handle the case where the transformations

- module.yaml
> removed credentials-managed-by: secret-provider

- afm/server.py
* respect nullable and metadata of fields
* remove redundant call when a scanner is used
> fix: filter_columns error

- Pipfile
- Pipfile.lock
> update version of schemed-yaml-config to update pyyaml version

- Pipfile
- Pipfile.lock
> update pyyaml version

- .github/workflows/build.yml
- .travis.yml
- Makefile
- helm/afm/Chart.yaml
- helm/afm/values.yaml
- module.yaml
Signed-off-by: Mohammad-nassar10 <mohammad.nassar@ibm.com>
> Add tag for release.

- module.yaml
> Change image.tag to 0.0.0 in M4DModule.

- module.yaml
Signed-off-by: Mohammad-nassar10 <mohammad.nassar@ibm.com>
> module.yaml should point to latest.

- Makefile
- helm/afm/values.yaml
> Change to latest tag in Makefile and helm/afm/values.yaml

- module.yaml
> Change label tag to latest in module.yaml

- module.yaml
Signed-off-by: Mohammad-nassar10 <mohammad.nassar@ibm.com>
> Add endpoint to module.yaml.

- README.md
Including version compatibility matrix
> Update README.md with instructions to register as a Mesh for Data module

- helm/afm/templates/service.yaml
Rename the service name to be *only* the release name.
Signed-off-by: tomersolomon1 <tomer.solomon1@gmail.com>
> Rename service name

- afm/server.py
- module.yaml
- sample/README.md
- sample/sample.yaml
- sample/sample_put.py
supports writing parquet dataset to filesystems
> added do_put()

- afm/filesystems/vault.py
> add error messages for vault authentication

- module.yaml
> replace 'source' with 'sink' for write

- .github/ISSUE_TEMPLATE/config.yml
- .github/workflows/build.yml
- README.md
- helm/afm/values.sample.yaml
- helm/afm/values.yaml
- module.yaml
> rename project to fybrik

- helm/afm/files/conf.yaml
WIP Please do not merge.
This PR contains changes to the arrow-flight configMap generation based on the smart blueprints changes.
> Change config map generation following smart-bluerints changes.

- .github/workflows/build.yml
Fix the build workflow to push the docker image and the helm chart with the appropriate tag when there is a new tag.
Closes #91 
Signed-off-by: Mohammad Nassar <mohammad.nassar@ibm.com>
> Fix the build workflow.

- module.yaml
Signed-off-by: Shlomit Koyfman <shlomitk@il.ibm.com>
Required for https://github.com/fybrik/fybrik/pull/1067
> Change "api" structure due to FybrikModule CRD change

- module.yaml
> Fix image tag in module.yaml

- README.md
> updating compatibility matrix

- Pipfile
- Pipfile.lock
- afm/auth.py
- afm/auth_handlers/auth_servers.py
- afm/config.py
- afm/filesystems/s3.py
- afm/filesystems/vault.py
- afm/logging.py
- afm/server.py
- helm/afm/files/conf.yaml
- main.py
First step in addressing task “Change the arrow flight service to generate log entries according to the new structure” from Issue https://github.com/fybrik/fybrik/issues/983 (“Data Plane: Generate log information in a standardized manner”). Does not address the “Change the data movement operator to generate log entries according to the new structure” task from [issue 983](https://github.com/fybrik/fybrik/issues/983).
This PR addresses:
1.	JSON logging
2.	Logging of fybrikapplication UUID
Remaining tasks:
1.	Check (and update as needed) log level of all messages, especially those marked as critical
2.	Move logging code to a separate fybrik logging library.
3.	The name of the logger (in this case ‘arrow-flight-module’) should be sent as an argument
4.	Pass log level from config file
5. …
> Standard logging

- helm/afm/values.sample.yaml
replace 'labels' with 'metadata'
> fix helm/afm/values.sample.yaml

- afm/asset.py
- afm/auth_handlers/auth_servers.py
- afm/filesystems/s3.py
- afm/filesystems/vault.py
- afm/logging.py
- afm/server.py
- main.py
Another step in addressing task “Change the arrow flight service to generate log entries according to the new structure” from Issue [fybrik/fybrik#983](https://github.com/fybrik/fybrik/issues/983) (“Data Plane: Generate log information in a standardized manner”). Does not address the “Change the data movement operator to generate log entries according to the new structure” task from issue 983.
This PR addresses:
- Update log levels of log messages. Add extra parameters as key-value pairs
- Fix date format
- Remove function names from log messages
Remaining tasks:
- Move logging code to a separate fybrik logging library.
- The name of the logger (in this case ‘arrow-flight-module’) should be sent as an argument
- Pass log level from config file
- Add tags such as "for_user"
- add JSON …
> Improve log

- hack/tools/test_module.sh
This PR contains the following changes to test_module.sh script:
- Update vault values.yaml file path in test_module.sh
- Avoid using sleep after fybrik deployment in test_module.sh (#123)
- Add cleanup section.
- Delete redundant sleep commands
- 
Closes #123
> Changes to test_module.sh script

- Pipfile
- Pipfile.lock
- afm/auth.py
- afm/auth_handlers/auth_servers.py
- afm/filesystems/s3.py
- afm/filesystems/vault.py
- afm/server.py
- main.py
> logging from external fybrik_python_logging library

- afm/asset.py
- afm/config.py
- afm/server.py
- helm/afm/files/conf.yaml
- helm/afm/values.sample.yaml
- sample/sample.yaml
Handle the capability field in the assets and extract the asset info from the configuration based on asset name and capability. 
In `do_get()` the asset should have 'read' capability and in `do_put()` it should have `write` capability.
Signed-off-by: nassarmu10 <mohammad.nassar@ibm.com>
Closes #131
> Handle assets with capability field.

- helm/afm/files/conf.yaml
> fix typo in conf.yaml

- afm/auth.py
- afm/auth_handlers/auth_servers.py
- afm/filesystems/vault.py
- hack/test-script/test.py
> add missing copyright headers where needed

- helm/afm/files/conf.yaml
- helm/afm/values.sample.yaml
Closes #141 
This PR adjust assets structure received as helm chart values: instead of `source` and `destination` it will contain a list of arguments,
> Adjust assets structure received as helm chart values 

- build/Dockerfile
Co-authored-by: Doron Chen <cdoron@il.ibm.com>
Closes #146
> Change log to emit messages by default

- afm/pep/actions.py
- helm/afm/files/conf.yaml
- module.yaml
- sample/sample.yaml
for instance to filter out information on minors
> add filtering based on age

- helm/afm/files/conf.yaml
- helm/afm/templates/NOTES.txt
> fix helm files: conf.yaml and NOTES.txt

- README.md
> remove redundancy from README

- Pipfile
- Pipfile.lock
> use logging library in regular PYPI

- Makefile
> remove warning message at the beginning of requirements.txt

- sample/sample.yaml
so that we don't attempt to filter based on age
on an XXXXXX column
> rearrange transformations in sample.yaml

- module.yaml
> port field should be string

- Pipfile
- Pipfile.lock
> upgrade versions of arrow and pandas

- README.md
- hack/make-rules/helm.mk
- hack/tools/install_helm.sh
This PR sets Helm version to 3.8.
Closes #120
> Set Helm version to 3.8

- .github/workflows/codeql-analysis.yml
- .github/workflows/pull-request.yml
- .github/workflows/push.yml
- .github/workflows/test-module.yaml
Signed-off-by: mohammad-nassar10 <mohammad.nassar@ibm.com>
> Update old github actions.

- README.md
Signed-off-by: mohammad-nassar10 <mohammad.nassar@ibm.com>
> Update version compatibility matrix.

- hack/test-script/Asset-0.7.0.yaml
- hack/test-script/fybrikapplication-0.7.0.yaml
- hack/test-script/sample-policy-0.7.0.rego
Signed-off-by: mohammad-nassar10 <mohammad.nassar@ibm.com>
> Add test files for version 0.7.0.

- build/Dockerfile
- helm/afm/templates/_helpers.tpl
- helm/afm/templates/deployment.yaml
- helm/afm/values.yaml
> Hardening pod security

- helm/afm/values.sample.yaml
> Update labels in values.sample.yaml

- hack/test_module.sh
> Minor fix to hack/test_module.sh

- module.yaml
temporary revert to the old fybrik v1alpha1 version to finish the fybrik PRs tests
Signed-off-by: Alexey Roytman <roytman@il.ibm.com>
> WILL BE REVERT . temporary revert to the old fybrik v1alpha1 version.

- module.yaml
Reverts fybrik/arrow-flight-module#183
> Revert "WILL BE REVERT . temporary revert to the old fybrik v1alpha1 version."

- .github/workflows/test-module.yaml
- hack/test_module.sh
This PR adds the option to get all tags of the module repo in can we want to checkout a tag.
> Fix test-module.yaml workflow.

- .env
- .gitignore
- Pipfile
- Pipfile.lock
- afm/asset.py
- afm/environment/environment.py
- afm/filesystems/s3.py
- afm/server.py
- helm/afm/templates/_helpers.tpl
- helm/afm/templates/deployment.yaml
- helm/afm/values.yaml
> Support tls connection between Vault and the module.

- Makefile
Co-authored-by: Doron Chen <cdoron@il.ibm.com>
> Fix pipenv command in Makefile

- Pipfile
> Use PYPI for Vault and TLS libs

- afm/filesystems/s3.py
> Remove reference to deprecated secret_provider from the code

- README.md
> Update version compatibility matrix in README.md.

- hack/test_module.sh
Relates to issue #199. temporary fix to make the test work.
> Specify katalog as the catalog used in test script.

- afm/asset.py
- afm/config.py
> support loading transformation plugins from a plugin directory

- build/Dockerfile
> mkdir -p /etc/plugins

- build/Dockerfile
> chown afm /etc/plugins

- helm/afm/files/conf.yaml
> set plugin_dir to /etc/plugins in helm chart

- hack/test-script/test.py
- hack/test_module.sh
> Fix module service name in test
